Include <linux/uaccess.h> rather than <asm/uaccess.h>.
Notes:
- For kernel versions < 2.6.18, include <asm/uaccess.h> since <linux/uaccess.h>
  doesn't exist.
- <linux/uaccess.h> includes <asm/uaccess.h>.
- <linux/uaccess.h> seems to pull in the header file defining mm_segment_t,
  fixing the following error for 4.15.0:
  > In file included from src/port.c:26:
  > /usr/src/linux-headers-4.15.0-65-generic/arch/x86/include/asm/uaccess.h:30:27: error: unknown type name 'mm_segment_t'; did you mean 'apm_event_t'?
  >  static inline void set_fs(mm_segment_t fs)
  >                            ^~~~~~~~~~~~
  >                            apm_event_t
- This header file is no longer even needed, since commit 701466a removed
  copy_*_user from `src/port.c'.